# Supply your provisioned app name with: fly deploy --app YOUR_APP
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.api"

[env]
  STACKS_DATA_DIR = "/app/web/public/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "512mb"
  cpus = 1
